---
driver:
  name: docker
  hostname: postfix.ci.local
  use_sudo: false

provisioner:
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  grains:
    noservices: True

platforms:
  - name: ubuntu-14.04
#  - name: ubuntu-16.04
#  - name: centos-7.1

